language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    - php: 7.4snapshot

install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --prefer-dist -n

script:
  - mkdir -p build/logs
  - phpdbg -qrr vendor/bin/phpunit

after_script:
  - travis_retry vendor/bin/php-coveralls -v
